global using Newtonsoft.Json;
global using HotelBookinSystem.WindowForm.Config;
global using System.Data;
global using System.Data.SqlClient;
global using FluentEmail.Core;
global using HotelBookinSystem.WindowForm.AppDbContextModels;
global using Microsoft.Extensions.DependencyInjection;
global using HotelBookinSystem.WindowForm.Services;
global using HotelBookinSystem.WindowForm.Query;
